# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  resourceGroupName: 'DevTestResourceGroup'
  location: 'eastUS'
  templateFile: 'main.bicep'
  varazureSubscription : 'PCS_Development(156859c7-c94a-4494-a2fd-f3fb88d2316d)'

pool:
steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevOpsSPN'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
            az group create --name $(resourceGroupName) --location $(location)

