# Starter pipeline


trigger:
- none

variables:
  serverName: 'azpipedbdemosvr.database.windows.net'
  varazuresubscription : 'PCS_Development(156859c7-c94a-4494-a2fd-f3fb88d2316d)'
  databaseName: 'azpipedbdemo'
  SqlUsername: 'pcsadmin'
  SqlPassword: 'passwd01'
  SqlFile: 'PCS_Workshop.sql'

pool:
  vmImage: windows-latest

steps:

  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureSubscription: 'PCS_Development(156859c7-c94a-4494-a2fd-f3fb88d2316d)'
      AuthenticationType: 'server'
      ServerName: $(serverName)
      DatabaseName: $(databaseName)
      SqlUsername: $(SqlUsername)
      SqlPassword: $(SqlPassword)
      deployType: 'SqlTask'
      SqlFile: $(SqlFile)
      IpDetectionMethod: 'AutoDetect'